import time
from pathlib import Path


_SUBDIRS = ("theses", "topics", "experiments")


_SCHEMA_DOC = """# palace schema

three layers:

- `theses/` — wings. high-level claims we're converging on.
- `topics/` — rooms. thematic clusters of experiments.
- `experiments/` — drawers. one page per run, verbatim.

`index.md` — catalog. regenerated by `cairn lint`.
`log.md`   — append-only event log. one line per event.
"""


def init(root: Path) -> None:
    root = Path(root)
    root.mkdir(parents=True, exist_ok=True)
    for d in _SUBDIRS:
        (root / d).mkdir(exist_ok=True)
    _ensure(root / "index.md", "# index\n\n(empty — run `cairn lint` to rebuild)\n")
    _ensure(root / "log.md", "# log\n\n")
    _ensure(root / "schema.md", _SCHEMA_DOC)


def _ensure(p: Path, content: str) -> None:
    if not p.exists():
        p.write_text(content)


def safe_page_path(root: Path, rel: str) -> Path:
    root = Path(root).resolve()
    if rel.startswith("/") or ".." in Path(rel).parts:
        raise ValueError(f"unsafe wiki path: {rel}")
    p = (root / rel).resolve()
    if not str(p).startswith(str(root) + "/"):
        raise ValueError(f"escape detected: {rel}")
    return p


def append_log(root: Path, kind: str, msg: str) -> None:
    log = Path(root) / "log.md"
    ts = time.strftime("%Y-%m-%d %H:%M:%S")
    with open(log, "a") as f:
        f.write(f"- {ts} {kind}: {msg}\n")


def rebuild_index(root: Path) -> None:
    root = Path(root)
    lines = ["# index", ""]
    for sub in _SUBDIRS:
        lines.append(f"## {sub}")
        pages = sorted((root / sub).glob("*.md"))
        if not pages:
            lines.append("_(empty)_")
        for p in pages:
            title = _first_heading(p) or p.stem
            lines.append(f"- [{title}]({sub}/{p.name})")
        lines.append("")
    (root / "index.md").write_text("\n".join(lines))


def _first_heading(p: Path) -> str | None:
    for line in p.read_text().splitlines():
        line = line.strip()
        if line.startswith("#"):
            return line.lstrip("#").strip()
    return None
